version: '3.9'

services:
  order:
    container_name: order
    image: order:v1
    environment:
      SERVER_PORT: 8080
      PROCESS_ORDER_ENDPOINT_URL: 8080
    ports:
      - "8082:8080"
    networks:
      - sales

  process-order:
    container_name: process-order
    image: process-order:v1
    environment:
      SERVER_PORT: 8080
      INVENTORY_ENDPOINT_URL: 8080
    ports:
      - "8081:8080"
    networks:
      - sales

  inventory:
    container_name: inventory
    image: inventory:v1
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - sales

networks:
  sales:
    driver: bridge